### ISSUE TITLE
Lint misfiring: "useless" transmute from reference to pointer

### ISSUE THREAD

**Issue by bfops** [Manishearth/rust-clippy#1115]
The `useless_transmute` lint fires even when the transmute is between types that can't be cast to one another, e.g. `&'static str` and `*const u64`.

**Comment by Manishearth** [comment]
You just need to cast twice there https://is.gd/FJp3Ck

You should avoid transmute as much as possible, because often there will be silent extra pointers introduced due to `ref` or `&self` which mean that you transmute the wrong pointer. `as` gives you some degree of type safety and the casts are explicit.

Also, beware: `&'static str` is a fat pointer. Might be preferably to use `std::raw` instead.

**Comment by bfops** [comment]
Ah of course, that works great. With type inference, I now have `foo as *const _ as *const _`, which is a little odd, but no `transmute`s. Thanks!
