### ISSUE TITLE
Functions taking ownership of mutable data that implement Copy

### ISSUE THREAD

**Issue by KasMA1990** [Manishearth/rust-clippy#1691]
Hey, I've spent some time pouring over `Copy` recently, and I keep coming back to this case where taking mutable ownership of data that has a `Copy` implementation feels like a bug. Look at this code:

```
#[derive(Debug, Clone, Copy)]
struct CustomDate(u64);

fn func1(mut date: CustomDate) -> CustomDate {
	date.0 = 1;
	println!("Func1: {:?}", date);
        date
}

fn main() {
    let mut date = CustomDate(0);
	println!("Main: {:?}", date);
	let date2 = func1(date);
	println!("Main: {:?}", date);
        println!("Main: {:?}", date2);
}
```

In `func1` I have no way of telling that `CustomDate` is `Copy`able without looking at its definition, so it would be easy for me to wrongly assume that I can mutate it without leaving stale data around. When taking ownership, that is at least what I would assume I was doing.

I have no idea if this is a common problem though, but I could see myself working in a big code base where several people, who don't all know all the different types completely, could make this mistake. Am I way off track in assuming this is worth linting against? And if no, is this something that can and should be added to clippy?

**Comment by KasMA1990** [comment]
Also if it's something a Rust noob might reasonably implement, I'd love to take a swing at it, but I can probably use some help on it :)

**Comment by oli-obk** [comment]
I'd be fine adding this as an allow-by-default lint and test it one some code bases.

I'm assuming you want it replaced with the following?

```rust
fn func1(date: &mut CustomDate) {
    date.0 = 1;
    println!("Func1: {:?}", date);
}
```

Note that `!Copy` types and `Copy` types behave the same in the generated code, just not in the semantics the compiler enforces. So you get those copies even with move types. So the lint could work for all types, no matter if they are copy or not?

Still might be undesired due to hard to use APIs when you end up having to copy manually even though it might be obvious that the function only makes sense when duplicating the object beforehand.

**Comment by oli-obk** [comment]
The easy part is detecting the function pattern, the medium part is making it robust (copy vs not copy), testing against real code and writing a suggestion.

**Comment by Manishearth** [comment]
Yeah, the problem is that there are plenty of legit use cases for this pattern.

The function isn't actually "taking mutable ownership", owning something always gives you the right to mutate it. It is taking ownership and using a mutable binding. If it hadn't it could have done the `let mut x = x` trick to make it mutable inside the body. So your issue arises from a misunderstanding of how ownership works here -- it's not a problem that would arise in a code base of multiple experienced people because that's not how `mut foo` bindings work. It is however, a problem that this isn't obvious, and it would be nice if we could figure out how to teach it better (via docs, or a lint, or something).

Allow lint is fine by me; it might be worth discouraging `mut foo` in general.

**Comment by KasMA1990** [comment]
Could you show me some of these use cases? I'd love to know what I'm missing :)

Huh, TIL. I actually thought moving ownership had to respect the initial mutability status of the data (so passing an immutable struct to a function taking a mutable binding to its input would fail to compile).

So when you're suggesting to discourage `mut foo` usage, it's because it creates the illusion of two different kind of ownership? Just so I'm completely following :)

**Comment by Manishearth** [comment]
> Could you show me some of these use cases? 

I mean, just, you take some data in, owned, and you need to locally mutate it. Not an uncommon task

> So when you're suggesting to discourage mut foo usage, it's because it creates the illusion of two different kind of ownership?

yes. though it's something you need to learn eventually

**Comment by KasMA1990** [comment]
Well doh. Something implementing `Copy` is still a special case in my mind, but I guess that's not actually true.

**Comment by KasMA1990** [comment]
I'm actually torn on implementing this now; on one hand I definitely see the value in forcing people to accept that taking ownership carries no guarantee of immutability, but on the other hand, I also like having `mut foo` as a contract (even just an informal one) which helps readability, and I'd hate to encourage people to break it.

Would it be better to create a lint against using shadowing to get mutability on owned values? That way you would still have a lint that makes people think ownership over again when they see it, and the code can be kept simpler to read because the reader can assume that mutability state is not changed.

**Comment by Manishearth** [comment]
> Would it be better to create a lint against using shadowing to get mutability on owned values? That

No, it's a common pattern.

This problem seems to largely be one that can be solved via docs, not lints.

**Comment by KasMA1990** [comment]
But is it a good pattern? Why not just declare the binding mutable in the first place if you need to do mutation somewhere?

And I tend to agree (especially if we want to be lax about changing mutability of owned items).

**Comment by Manishearth** [comment]
Well, sometimes you don't want it to be mutated except for a small amount.


```
let mut x = foo();
x.mutate();
let x = x;
```

is a _very_ common pattern for this, but I've seen the reverse too. But yeah, the reverse is rarer.

**Comment by KasMA1990** [comment]
That makes sense; doing the needed mutation and locking it down seems like good use of shadowing. I'd still be in favor of a lint to catch shadowing of an immutable binding to a mutable one though; such a pattern being freely available means I generally can't trust that a value I think is immutable will remain unmutated, so a lint for it would be very nice.

**Comment by KasMA1990** [comment]
And should I close this issue and create a new one to discuss that lint instead?

**Comment by Manishearth** [comment]
Yeah, that would be preferred
