### ISSUE TITLE
bad_shift

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#211]
A value is shifted by more bits than the type allows for, e.g. `42u8 << 9` or 1234i64 >> 64.

The idea is to check for `ExprBinary` with a `BiShl`/`BiShr` op where the second operand is a constant (use `const::constant(..)`) larger than or equal to the size of the type (get with `expr_ty(..)` of the first operand.

**Comment by Robzz** [comment]
This sounds easy enough. I'll probably have a go at it, unless someone else wants to try getting their hands dirty on an easy issue.

It's worth noting that the [rust reference](http://doc.rust-lang.org/reference.html#bitwise-operators) mentions that the bit shift operators are syntactic sugar for the `ops::Shl::shl` and `ops::Shr::shr` method calls, so for completeness, it might be a good idea to check for these. (related : we might want to add a second lint to warn that the `>>` and `<<` operators are more concise and, arguably, clearer?)

There is also the case of `isize`/`usize`, their width being arch dependent. To be coherent with what you suggested in #208, I would suggest warning whenever an `*size` is shifted by 32bits or more.

In case somebody else wants to to this, I'll also mention that since Shl and Shr are only implemented for integer types (well, and simd::* structs, but these have been deprecated in the current beta), the function `types::in_ty_to_nbits` could be used, although it would need to be made public if the lint is located in another module.

**Comment by llogiq** [comment]
Knock yourself out :smile:.

**Comment by Robzz** [comment]
[It would seem rustc already errors about this.](https://play.rust-lang.org/?code=%2F%2F%20This%20code%20is%20editable%20and%20runnable!%0Afn%20main%28%29%20{%0A%20%20%20%20println!%28%22{}%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%205u32%20%3C%3C%2032%29%3B%0A}%0A&run=1)

**Comment by Manishearth** [comment]
Nice catch :smile:
