### ISSUE TITLE
false positives from the `.iter()` lint

### ISSUE THREAD

**Issue by birkenfeld** [Manishearth/rust-clippy#236]
In racer, there's an iteration over an `OwnedSlice` from syntex:
https://github.com/phildawes/racer/blob/master/src/racer/ast.rs#L742

In this case, using `for ty in &g.ty_params` does not work (must have something to do with autoderef). The lint currently flags this anyway.

**Comment by llogiq** [comment]
Interesting. This autoderef business sure complicates stuff like this. If only it wasn't so damn convenient. :smile:

I think the problem is that `&OwnedSlice<T>` does not deref to `&[T]`, but to `OwnedSlice<T>`, which does deref to `[T]` (instead of `&[T]`), which does not implement `IntoIterator`. So the solution for this particular case would be to `impl IntoIterator for &OwnedSlice`.

The solution to get rid of the false positives is to follow the deref chain until we find an `IntoIterator`-implementing type.

**Comment by Manishearth** [comment]
We were having similar trouble in Servo, some of the lints needed `for ty in &*g.ty_params`, and others were using types with an `iter` method that wasn't from `IntoIterator` (but should have been). Most of these were from an era before `IntoIterator`.

**Comment by birkenfeld** [comment]
Hm, given type `T` I'm not sure how I would check that `&T` or `&mut T` (which don't necessarily occur in the typechecked code) implements `IntoIterator`.

Maybe it's best to restrict this to `Vec` and `slice` types, and maybe a few others from `collections` that have iter methods...

**Comment by Manishearth** [comment]
whitelist sgtm for now, might want to file an E-hard issue for making this smarter.

Might also want to wait post-MIR to make this smarter :)
