### ISSUE TITLE
LintPassObject and Context do not exist on latest nightly.

### ISSUE THREAD

**Issue by Sean1708** [Manishearth/rust-clippy#338]
The former is now (Early/Late)LintPassObject and the latter appears to have been removed, both in [this](https://github.com/rust-lang/rust/commit/a642d853aa29f8ec8486e736be551cf77f34e219) commit.

For reference:

    $ rustc --version
    rustc 1.5.0-nightly (cff041170 2015-09-17)

**Comment by Sean1708** [comment]
Perfect, thanks for doing this so quickly.

**Comment by llogiq** [comment]
@Manishearth Do you know how this split affects us? Of course, our current lints are written to run *after* expansion + type checking, but we could also have lints that could run better pre-expansion.

**Comment by Manishearth** [comment]
There are now AST lints and HIR lints. HIR lints are what the original lints were, AST lints are similar but can't access the `tcx`. We can move some lints over to AST if we wish.


The operator precedence lint needed to be moved to AST since ExprParen was removed from the HIR (it's not an Expr, it's a parsing artefact that should go away), so that check is only valuable on the AST.

**Comment by llogiq** [comment]
Ah, that's good to know. How should we lint things that require both access to the original AST and e.g. type information?

**Comment by Manishearth** [comment]
HIR lints don't lose access to the AST.

ExprParen is just a weird thing that shouldn't be part of the AST in the first place.

**Comment by llogiq** [comment]
OK, lints that want to know if there are parens can parse the code snippets directly.
