### ISSUE TITLE
bad comparison of upcasted values

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#42]
E.g. `let x : u8 = ...; x as u32 > 300` maybe check sign of casted previously unsigned values.

**Comment by creativcoder** [comment]
I would like to work on this. Can you please elaborate more about this issue ?

**Comment by Manishearth** [comment]
So here we need to check for situations where we are casting before comparing, i.e. `x as u32 > 200` or `x as u32 < 0`, and the original type has a range such that the comparison will always be true or always be false.

...actually, this isn't really an easy bug since you have to look up the value of `x`  and ensure its not getting written to.

**Comment by Manishearth** [comment]
#97 should be easier. Its a simple check_ty with most of the details explained in the last comment. There are some complications there but I'll explain how to handle them when we reach that stage.

**Comment by llogiq** [comment]
I don't think so. It should suffice matching a comparison where one of the operands is an ExprCast whose inner expression has a primitive type that is smaller than the comapred value (via expr_ty)

**Comment by Manishearth** [comment]
Ah, I misunderstood the issue. In that case this isn't too hard.
