### ISSUE TITLE
if x != y { a }  else { b } should be if x == y { b } else { a }

### ISSUE THREAD

**Issue by oli-obk** [Manishearth/rust-clippy#469]
Suggest using the equality comparison operator instead of inequality if the arms can be trivially swapped. Inequality is one more indirection to think about, so using equality is easier to comprehend.

**Comment by oli-obk** [comment]
The same should probably be done for inverting a boolean value:

```rust
if !v.is_empty() {
    a();
} else {
    b();
}
```

should be 

```rust
if v.is_empty() {
    b();
} else {
    a();
}
```

**Comment by fhartwig** [comment]
Could we make this `Allow` by default? I think that for non-trivial branches, the order of the branches can be more important for readability than the extra negation in the condition.

**Comment by Manishearth** [comment]
Sounds good. Also okay with it being warn.

**Comment by oli-obk** [comment]
@fhartwig do you have an example?

**Comment by fhartwig** [comment]
@oli-obk If I have an if-else where one of the branches is much more complex than the other I like to put the shorter/less complex one first (because putting the more complex one first means that I lose track of the context and have to go back to check what the condition is when I reach the `else` branch.).

**Comment by oli-obk** [comment]
The clean way would be to separate out the second branch into a function, so you don't loose the context after the entire if/else block.
