### ISSUE TITLE
needless unsafe

### ISSUE THREAD

**Issue by llogiq** [Manishearth/rust-clippy#505]
lint `unsafe fn`s (or blocks) which contain only safe operations

**Comment by crumblingstatue** [comment]
Rust already has an `unused_unsafe` lint that does this.

@rphmeier talks about a different kind of lint in rust-lang/rfcs#1411, where the desired effect would be to warn about doing unsafe operations without an explicit `unsafe { ... }` block in unsafe functions.

**Comment by rphmeier** [comment]
The problem with that is that it conflicts with rust's lint against unused_unsafe, as seen here: http://is.gd/mNGqZS.

This is really a stylistic choice: while explicitness is usually nice, it's clear from the rustc/std source code that grouping together unsafe statements with associated safe statements is understandably valued by the developers. Furthermore, it's more in line with the concept of `unsafe` polluting an entire *module* rather than just its block or function. I suggest closing this issue since either such lint would probably not assist developers in productivity.
