### ISSUE TITLE
Regex: Inform user about slow regex! macro

### ISSUE THREAD

**Issue by killercup** [Manishearth/rust-clippy#595]
As discussed in #587, the `regex!` compiler plugin is currently slower than the runtime based `Regex::new`. We should inform the user about that.

**Comment by llogiq** [comment]
I have built the lint, but I still have to stop it from matching all parts of the macro expansion. @BurntSushi is there an expression that all `regex!` expansions have in common?

**Comment by BurntSushi** [comment]
@llogiq Hmm, good question! That's actually pretty tricky to answer. The [code is here](https://github.com/rust-lang-nursery/regex/blob/master/regex_macros/src/lib.rs). I think for the forseeable future, if you find a type with the letters `nfa` in them (ignoring case), then that should be sufficient.

**Comment by llogiq** [comment]
Oh, I can already check if an expression is part of the macro expansion. Unfortunately, the lint matches multiple times per `regex!(_)`.

**Comment by BurntSushi** [comment]
@llogiq Ah, so you need a uniquely identifying expression? Can you use a type definition? e.g.,

```rust
struct Nfa<'t>
```

**Comment by llogiq** [comment]
Hmmm... I think I'll try to use the outer block then (and a Visitor to skip walking when found).

**Comment by llogiq** [comment]
I have a [regex_macro](https://github.com/Manishearth/rust-clippy/tree/regex_macro) branch with my current code. Even using blocks doesn't keep it from being run multiple times. Either I'll have to go crate-(or at least module-) wide instead of function wide and keep the matched positions in some kind of set to remove the duplicate warnings, or someone finds a better solution. cc @Manishearth
