### ISSUE TITLE
Add warning when declaring binding with type `()`

### ISSUE THREAD

**Issue by killercup** [Manishearth/rust-clippy#74]
I just read https://internals.rust-lang.org/t/two-little-proposals/2148 and @Xirdus' first proposal sounds like a good addition to clippy:

> Make it a warning (or even an error) to declare a variable of type (), except when it's due to generic type resolution. This is pretty useless, but some people new to Rust might do it by mistake, for example by saving the result of assignment. Also would make finding errors like unwanted semicolon easier in some cases.

**Comment by Manishearth** [comment]
Sounds good to me.

**Comment by llogiq** [comment]
So we'd match on let and see if we find a unit type in there – should we only match the immediate type or also part of tuple types? I would not match on vecs/slices, because that may trip up some `collect()` / `count()` calls. Also we'd obviously re-use the macro check from mut_mut (once we agree it's sufficiently reliable). Generics should not present a problem, as they have their own representation in the AST.

Would we also warn on `fn` args of type unit?

**Comment by Manishearth** [comment]
I think nested tuples may have false positives, and they don't really help the case at hand.

The problem is `let y = (let x = foo())` type expressions. We take `let x = ...` and run expr_ty on the RHS to check for `()`

**Comment by llogiq** [comment]
Ok, so only direct types. What about args?

**Comment by Manishearth** [comment]
I don't see antything wrong there. Perhaps we should warn on `foo(unit_expr)` where `foo()` is generic
