### ISSUE TITLE
Cyclomatic complexity for large switch-type match

### ISSUE THREAD

**Issue by birkenfeld** [Manishearth/rust-clippy#869]
I have a large switch-type matching method in my crate, [see here](https://github.com/birkenfeld/serde-pickle/blob/master/src/de.rs#L143).

Clippy says it has a complexity of 84, but I'm not sure what else I can do to make it simpler. Most of the match arms just call a few functions and have no branches anymore.

Does the complexity calculation need adjustment? Is it counting the `try`s as branches?

**Comment by oli-obk** [comment]
A `try!` is treated like an if+else, so it adds 1 to the cc

**Comment by birkenfeld** [comment]
Ok. That follows the definition for the cc faithfully, but given the special status of `try!` (which will later become `?`) in Rust, should we ignore it instead?

**Comment by llogiq** [comment]
Yeah, think it should at most add 0.5 to the cc :smile:

**Comment by oli-obk** [comment]
I could change matches to act as 0.5 in general, since they are special. This would mean that changing an if/else to a match would decrease the cc

**Comment by llogiq** [comment]
I don't like this, because *in general* this is not the case, e.g. `if x { foo() } else { bar() }` is not more complex than `match x { true => foo(), false => bar() }`.

However, as it stands we unduly punish error handling, and since the `try!` notation (or even `?` syntax) does not visually clutter the code too much (not to mention that it doesn't add to indentation, which both `if` and `match` do), we should either not count them at all or at a greatly reduced cost. Perhaps even 0.5 is too large. Make that something in the [0..0.1] range.

**Comment by oli-obk** [comment]
I'll look what I can do, but it's a little hard, because control flow and syntax are quite at odds with each other. Currently I'm computing cc by running through the control flow graph and then reducing it by counting match arms and diverging calls. Alternatively I could start computing the control flow graph manually from the AST, this way macros would be treated as function calls (no cc increase). But I'm not sure how hard that is.

**Comment by llogiq** [comment]
You may be able to use the `AST(NodeID)`s to match the branches of the `CFG` to a node, which you could then check with `utils.is_expn_of(..)` if the branch is a `try!` (however this will fail with the new `?` syntax, this will probably some other expansion).

**Comment by oli-obk** [comment]
We could also do a more general thing and decrease the CC by 1 for every early return. Yes it's another path through the function, but most of the time you are doing it to prevent rightwards drift.

**Comment by oli-obk** [comment]
even better, we could specialize for returning a `Result` early!

**Comment by llogiq** [comment]
IMHO, that's both good ideas – increase CC only by 0.5 for non-Result-bearing early returning branches, and don't increase CC at all for Result-returning branches.
